### ISSUE TITLE
Example from readme does not seem to work

### ISSUE THREAD

**Issue by andrewmartz-af** [aldeed/meteor-cfs-autoform#10]
Is anyone else having this problem with the example code from the readme?

![screen shot 2014-12-03 at 5 10 49 pm](https://cloud.githubusercontent.com/assets/5732673/5291973/6b4de4d8-7b0f-11e4-9247-9901c9d6a4b6.png)

**Comment by takahser** [comment]
didn't work for me neither, even when I use all the packages mentioned.
My form just displays "File id" but no file input (I'm using materialize css):

```
<div class="row">
    <div class="input-field col s12">
        <label for="dSxH8YW9NGdE4ZvhG">
            File id
        </label>
    </div>
</div>
```

my setup:
- Meteor 1.2.1
- cfs:autoform                       2.2.1
- cfs:gridfs                         0.0.33
- cfs:standard-packages              0.5.9
- insecure                           1.0.4
- aldeed:autoform                    5.8.1
- aldeed:collection2                 2.8.0
