### ISSUE TITLE
validate as image

### ISSUE THREAD

**Issue by advany** [aldeed/meteor-cfs-autoform#18]
Is there a way to validate it as an image? both server and client side?

**Comment by aldeed** [comment]
CFS can validate that it's an image, but there's currently nothing that feeds back into autoform validation automatically.

**Comment by advany** [comment]
great! got that to work using allow: {
      contentTypes: ['image/*'],
      extensions: ['png', 'jpg', 'jpeg', 'gif']
    }

It gives alerts.

**Comment by advany** [comment]
When I update an object, with a existing file, it removes the fileid. Is there a way to preserve it?

**Comment by aldeed** [comment]
Update forms aren't supported yet, so you should omit the field from your update forms.

**Comment by advany** [comment]
Thnx for helping out! I am just getting started with meteor and js. Or else I would have helped out developing the remaining todo's...
