### ISSUE TITLE
Multiple file upload

### ISSUE THREAD

**Issue by howardrn** [aldeed/meteor-cfs-autoform#19]
Hello,

I had to amend to following code (in a local package clone of cfs:autoform)  in order to allow me to upload multiple files. ;-

if (arrayFields[key]) {
var temp = CfsAutoForm.Util.deepFind(doc,key)
temp[key].push(fileObj._id);
} else {
//doc[key] = fileObj._id;
CfsAutoForm.Util.deepSet(doc,key,fileObj._id

in the cfs-autoform-hooks.js file beginning line 68. Otherwise I was getting an error of "undefined function" as "deepFind"  was returning an object with both the "name" property and the "fileId" property.

Basing on your example on your site, I have changed the "Docs" Schema property "fileId" to [String] and changed the attribute "cfs-files", otherwise the form validation did not work.

Now multiple uploads (ie. one Name (In Docs) and mulitple files/images attached to it) all works splendidly ! I have no problem retrieving images.... I convert the "FileId" object which is held in MongoDb as "[hfiufhrifuhirhf,hkhkfhsdkfhm,hfshkshfksh]" to ["hfiufhrifuhirhf","hkhkfhsdkfhm","hfshkshfks"] in order to use it in this  code 

temp = ["hfiufhrifuhirhf","hkhkfhsdkfhm","hfshkshfks"]
Files.find({_id: {$in: temp}})

which returns just those images which pertain to the selected name.

Apologies in advance if I have made the changes in a daft way, but I am not a professional programmer, just a 61 year old hobbyist !.

Grateful if you could steer me on better solution.

Rgds

Howard

**Comment by howardrn** [comment]
Please disregard the above portion of text :-

Quote
.... I convert the "FileId" object which is held in MongoDb as "[hfiufhrifuhirhf,hkhkfhsdkfhm,hfshkshfksh]" to ["hfiufhrifuhirhf","hkhkfhsdkfhm","hfshkshfks"] in order to use it in this code

temp = ["hfiufhrifuhirhf","hkhkfhsdkfhm","hfshkshfks"]
Files.find({_id: {$in: temp}})

which returns just those images which pertain to the selected name.

Unquote

I haven't explained it well enough.

MonoDB was indeed holding the data correctly as  ["hfiufhrifuhirhf","hkhkfhsdkfhm","hfshkshfks"] . The array "[hfiufhrifuhirhf,hkhkfhsdkfhm,hfshkshfksh]", was being returned  from the Value property of an Options Tag  which was holding my FileId property which in the schema was type [String].

**Comment by jsmith0295** [comment]
I had this problem as well and the same modification fixed it for me.
