### ISSUE TITLE
Multiple file upload

### ISSUE THREAD

**Issue by ghost** [aldeed/meteor-cfs-autoform#3]
This project looks good so far. Does it currently support multiple file upload? I saw that it handles it on the front-end but I have been having trouble getting it to store an array of file Ids. I could be doing something wrong. Autoform and the related projects are new to me as well.

**Comment by tarekw** [comment]
Hi, I'm trying to use this package to upload multiple image. Just tried the template you mentioned above but it seems to complain that there is no such template cfsFileField. My version is 2.2.1. Am trying to use the template inside an autoform.
