### ISSUE TITLE
I keep getting: "Uncaught TypeError: Cannot read property 'insert' of undefined"

### ISSUE THREAD

**Issue by adim86** [aldeed/meteor-cfs-autoform#34]
I am using cfs-filesystem with the autoform and I have set it up using both the documentation in the  collectionFS and meteor-cfs-autoform but I am getting the error above when i try to submit a form creating a record for my school collections. I am not sure what I am missing or where the error is getting generated

common.js:
<pre><code>
// File methods
Images = new FS.Collection("images", {
  stores: [new FS.Store.FileSystem("images", {path: "~/img/uploads"})]
});

Images.allow({
  download: function () {
    return true;
  },
  fetch: null
});
</pre></code>
school_collection.js:
<pre><code>
chools = new Mongo.Collection("Schools");

//Defining the schema
Schools.attachSchema(schoolSchema = new SimpleSchema({
  name: {
    type:String,
    label: "Name",
    max:200
  },
  primary_color: {
    type:String,
    label: "Color",
    optional: true
  },
  sub_domain: {
    type:String,
    label: "Sub Domain",
    max:50
  },
  user_id:{
    type: String,
    autoform: {
      type: "hidden",
      label: false
    },
    autoValue: function(){
      if (this.isInsert) {
            return Meteor.userId();
        } else if (this.isUpsert) {
            return {$setOnInsert: Meteor.userId()};
        } else {
            this.unset();
        }
      },
    denyUpdate:true
  },
  image: {
    type: String,
    label: "Logo",
    autoform: {
      afFieldInput: {
        type: "cfs-file",
        collection: "files"
      }
    }
  }
}));
</code></pre>

school_create.html
<pre><code>
<template name="school_create">
  <div class="header">School Create</div>

  {{#autoForm collection="Schools" id="school_create" type="insert"}}
    <fieldset>
      <legend>Add a School</legend>
      <div style="float:left">
        <div class="textField">
          {{> afQuickField name='name'}}
        </div>
        <div class="textField" style="margin-left:20px;">
          {{> afQuickField name='sub_domain'}}
        </div>
        
      </div>
      <div class="descriptionText">
        {{> afQuickField name="image"}}
      </div>
    </fieldset>
    <button type="submit" class="btn btn-primary">Add a School</button>
  {{/autoForm}}
  
</template>
</code></pre>

**Comment by adim86** [comment]
Figured it out. Was using the wrong collection in the autform

**Comment by ndramirez** [comment]
So, what was the correct collection? It wasn't "Schools" ?

**Comment by StillOnMyWay** [comment]
@ndramirez I think he may have meant that he used the wrong collection in the Schema definition of the image attribute. It was "files" in the schema, but "images" in the FS.Collection definition.
